### ISSUE TITLE
请问计算损失函数时是不是只考虑被替换的token？

### ISSUE THREAD

**Issue by RookieZB** [ymcui/MacBERT#1]
谢谢。

**Comment by ymcui** [comment]
是的，这一点与原版的MLM是一致的。
收集所有mask（广义：包括近义词替换、随机替换、不替换）的位置，然后再处理。
可参考：https://github.com/google-research/bert/blob/master/run_pretraining.py#L240

**Comment by RookieZB** [comment]
明白，谢谢。
