### ISSUE TITLE
中文单个字符如何找到同义词的

### ISSUE THREAD

**Issue by AlexYoung757** [ymcui/MacBERT#2]
论文中提到摸型对单字符的概率是40%，对于英文来说，比较容易找到单个字符的同义词，但是单个字符对于中文来说，大概率是无法找到同义词的。难道要把这么多找不到同义词的使用随机替换？请问是如何处理的？
代码到时候会开源吗

**Comment by ymcui** [comment]
不是单字符是40%，是unigram，以词为粒度。

**Comment by AlexYoung757** [comment]
> 不是单字符是40%，是unigram，以词为粒度。
懂了。具体训练细节会公布出来吗
