### ISSUE TITLE
请问MacBERT的参数和RoBERTa-wwm的参数是兼容的吗？

### ISSUE THREAD

**Issue by daizh** [ymcui/MacBERT#4]
原先适配[RoBERTa-wwm](https://github.com/ymcui/Chinese-BERT-wwm)的模型代码是否直接换一个MacBERT的checkpoint就能直接fine-tune呢？

**Comment by ymcui** [comment]
可以的，finetune方面可以直接替换，主体架构是一样的。

**Comment by daizh** [comment]
好的，谢谢您
