### ISSUE TITLE
词表中的<S>和<T>含义

### ISSUE THREAD

**Issue by zyccyz** [ymcui/MacBERT#6]
您好，我看到预训练词表中有两个特殊的token，请问这两个特殊token有何含义？在预训练中是否使用过？还是仅仅只是类似unused的随机初始化？希望能得到您的回复。

**Comment by ymcui** [comment]
预训练的过程中并没有使用。词表继承了谷歌原版中文词表，没有添加额外的token。

**Comment by zyccyz** [comment]
懂啦，感谢您的回复！
