### ISSUE TITLE
能否新增一个bort模型呢？

### ISSUE THREAD

**Issue by chadqiu** [ymcui/MacBERT#7]
Amazon在https://arxiv.org/pdf/2010.10499.pdf这篇论文中提到搜索出了Bert的最优子结构bort，目前huggingface上已经有了英文版，但还没有中文版的，非常期待一个中文版的bort出现，如果贵单位能训练一个出来就非常感谢啦

**Comment by ymcui** [comment]
感谢建议，我们会评估一下。
